dist: bionic
language: generic
keys:
  - SIGN_KEY
before_script:
  - travis_key SIGN_KEY cosign.key
script:
  - cat cosign.key
  - docker build . -t testtest
  - cosign sign --key cosign.key testtest
