dist: bionic
language: generic
keys:
- SIGN_KEY
before_script:
- travis_key SIGN_KEY cosign.key
script:
- cat cosign.key
- docker build . -t testtest
- cosign -version
- cosign sign --key cosign.key testtest
env:
  global:
    secure: OPcjuRFkAzm/ZRv94gAJ2OG1YGLgiIkQQ0M6WlXjgR0dxgFY+snDDPJvznydnuTuKDOnBd99PLZEXVgPqPcH2dfA0BSK9nIyQw36xl2xjrhnCatQ6p3pKr8xP8SMkhBqXCO1wz+ECpKwWFnRHE2oc4eNqf/KKpCGUv4eabF6p+d7ZQz8FkhW1kWTZ6O0jMnV4PfBq9G1pLxHglvdDZwjdod7hMYsS5XokpMKWyv/YL3ELrdMWKgPlim7P5QRRqDl+J+7Vcq9v0RWQL3FLaEV/nvRG9BTM6hIQYvnimjzVSBqvEGoRYa4Clw0SyWTcZus9Ufss7wg2oKAu48ZaktcjYn4PBoDVr2CV01LVk70p2/0A2L4BE4KvkGDZ4lduwn+h6Id3sNVdbC0aocPKHfp+OL28nDA7eIaQeAvLddyynEs3R7ST2EwfyjhWl914DLLJ5cCS1m8i3w12qBXR9uWzaESTcN9y5f9gKV0ek2KWN2Ui3ymVbAmXc/iP4IzAjAcQSHD42VDl5UCW0WEDNSIqXBNv6Gpd1jhJb+YQLHUeuCm8C3V3Uyf7z+/DLLtn/VpRG+YCIxPiffHIY7imnRbD64j+//PI1yOtZd7Gtqp11g8V6K9k47qAyrI69uYmAxJbrvEuOCoVekBMw0no3x6BsKoJ2dVG0Ya8EVZ6jcRJg0=
