dist: bionic
language: cpp
env:
  global:
  - RUN_TESTS=true

stages:
- name: testing
  if: env(RUN_TESTS) =~ /^(?i)(true|1).*/
- name: no_testing
  

jobs:
  include:
    - stage: testing
      script: echo "RUNNING TESTS"
    - stage: no_testing
      script: echo "some stage"
    
