dist: bionic
language: generic
cache:
    directories:
     - /home/travis/cachetest/
script:
- mkdir -p /home/travis/cachetest/
- cat /home/travis/cachetest/testtest || true
- date >> /home/travis/cachetest/testtest
